<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ProfessionalsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('professionals')->insert([
            [
                'name' => 'Ali Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ali@gmail.com',
                'image' => 'team-1.jpg',
                'cv' => 'Ali_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 30,
                'gender' => 'Male',
                'price' => 5.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 50,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Omar Ahmad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Omar@gmail.com',
                'image' => 'pro2.png',
                'cv' => 'Omar_cv.pdf',
                'location' => 'Amman',
                'experience' => 17,
                'age' => 37,
                'gender' => 'Male',
                'price' => 8.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 132,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Saturday',
                'hoursofwork' => '9am,12pm,2pm,5pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ahmad salih',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ahmad@gmail.com',
                'image' => 'pro1.png',
                'cv' => 'Ahmad_cv.pdf',
                'location' => 'Aqaba',
                'experience' => 12,
                'age' => 33,
                'gender' => 'Male',
                'price' => 8.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 65,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sara Ali',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Sara@gmail.com',
                'image' => 'pro3.png',
                'cv' => 'Sara_cv.pdf',
                'location' => 'Irbid',
                'experience' => 15,
                'age' => 40,
                'gender' => 'Female',
                'price' => 10.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 66,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ibrahim Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ibrahim@gmail.com',
                'image' => 'team-2.jpg',
                'cv' => 'Ibrahim_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 32,
                'gender' => 'Male',
                'price' => 6.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 56,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maryam Ahmad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Maryam@gmail.com',
                'image' => 'team-4.jpg',
                'cv' => 'Maryam_cv.pdf',
                'location' => 'Aqaba',
                'experience' => 5,
                'age' => 29,
                'gender' => 'Female',
                'price' => 7.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 30,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ali Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ali@gmail.com',
                'image' => 'team-1.jpg',
                'cv' => 'Ali_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 30,
                'gender' => 'Male',
                'price' => 5.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 50,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ali Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ali@gmail.com',
                'image' => 'team-1.jpg',
                'cv' => 'Ali_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 30,
                'gender' => 'Male',
                'price' => 5.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 50,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ali Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ali@gmail.com',
                'image' => 'team-1.jpg',
                'cv' => 'Ali_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 30,
                'gender' => 'Male',
                'price' => 5.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 50,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ali Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ali@gmail.com',
                'image' => 'team-1.jpg',
                'cv' => 'Ali_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 30,
                'gender' => 'Male',
                'price' => 5.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 50,
                'provider_id' => 4, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ali Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ali@gmail.com',
                'image' => 'team-1.jpg',
                'cv' => 'Ali_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 30,
                'gender' => 'Male',
                'price' => 5.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 50,
                'provider_id' => 3, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ahmad salih',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ahmad@gmail.com',
                'image' => 'pro1.png',
                'cv' => 'Ahmad_cv.pdf',
                'location' => 'Aqaba',
                'experience' => 12,
                'age' => 33,
                'gender' => 'Male',
                'price' => 8.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 65,
                'provider_id' => 3, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sara Ali',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Sara@gmail.com',
                'image' => 'pro3.png',
                'cv' => 'Sara_cv.pdf',
                'location' => 'Irbid',
                'experience' => 15,
                'age' => 40,
                'gender' => 'Female',
                'price' => 10.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 66,
                'provider_id' => 3, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ibrahim Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ibrahim@gmail.com',
                'image' => 'team-2.jpg',
                'cv' => 'Ibrahim_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 32,
                'gender' => 'Male',
                'price' => 6.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 56,
                'provider_id' => 1, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ibrahim Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ibrahim@gmail.com',
                'image' => 'team-2.jpg',
                'cv' => 'Ibrahim_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 32,
                'gender' => 'Male',
                'price' => 6.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 56,
                'provider_id' => 2, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],         [
                'name' => 'Ibrahim Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ibrahim@gmail.com',
                'image' => 'team-2.jpg',
                'cv' => 'Ibrahim_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 32,
                'gender' => 'Male',
                'price' => 6.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 56,
                'provider_id' => 5, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ibrahim Mohammad',
                'user_id'=> 1,
                'description' => 'I\'m a specialist in attention to detail in every aspect of my business, and believe in great customer service, and because I understand the adage "home is where the heart is" I strive to be careful, and I endeavor to afford my clients with a truly professional, competitive service.',
                'email' => 'Ibrahim@gmail.com',
                'image' => 'team-2.jpg',
                'cv' => 'Ibrahim_cv.pdf',
                'location' => 'Irbid',
                'experience' => 9,
                'age' => 32,
                'gender' => 'Male',
                'price' => 6.00,
                'profission' => 'Profession in wall painting and interior designing',
                'completed_jobs' => 56,
                'provider_id' => 6, // Assuming this references a provider
                'image1' => 'image_png (3).png',
                'image2' => 'image_png (4).png',
                'image3' => 'image_png (5).png',
                'image4' => 'image_png (6).png',
                'image5' => 'image_png (7).png',
                'image6' => 'image_png (8).png',
                'daysofwork' => 'Monday,Tuesday,Wednesday',
                'hoursofwork' => '8am,9am,12am,3pm',
                'created_at' => now(),
                'updated_at' => now(),
            ]
            // Add more professional records as needed
        ]);
    }
}
